-- io.output("myFile2.txt")
-- io.write("hello world!!!!!")
io.input("myFile.txt")
-- local file = io.read(100)
-- local fileLineT = io.read("*all")
io.input("myFile2.txt")
-- local fileOpen = io.open("MyFile.txt", "w")
-- local fileOpen = io.open("MyFile.txt", "a")
-- fileOpen:write("\nhehehihi")
local fileOpen = io.open("MyFile.txt", "r")
local fileRead = fileOpen:read("*all")
local fileNumber = io.read("*number")
io.close()
-- print(file)
-- print(fileLineT)
print(fileRead)
print(fileNumber)